# input data
accessions: data/NCBI_Virus_229E_accessions.csv
addtl_accessions_metadata: data/extra_229E_accessions_metadata.yaml
accessions_special: data/accessions_to_include_exclude_annotate.yaml
domain_annotated_spike: data/AAK32191_hand_annotated.gp

# options for analysis
redownload_genbank: false  # re-download Genbank seqs even if exist
email: jbloom@fredhutch.org  # needed to download from Genbank
prot_length_range: [1170, 1174]  # keep Spikes in this length range, inclusive
remove_redundant_prot: true  # only keep one of redundant proteins?

pdb_id: 6u7h  # PDB identifier for structure
pdb_chains: [A, B, C]  # chains in PDB that are Spike

# parameters for designing sequences for experiments
c_term_del_len: 19  # delete this many amino acids from C-terminus

# name of created (results) files / directories
results_dir: results
genbank_seqs_dir: results/genbank_seqs  # download sequences here
spikes_unaligned_nt: results/spikes_unaligned_nt.fasta
spikes_unaligned_prot: results/spikes_unaligned_prot.fasta
spikes_metadata: results/spikes_metadata.csv
spikes_aligned_codon: results/spikes_aligned_codon.fasta
spikes_aligned_prot: results/spikes_aligned_prots.fasta
gard_recomb_json: results/gard_recomb.json
gard_recomb_best: results/gard_recomb_best.txt
divergencetree: results/timetree/divergence_tree.newick
timetree: results/timetree/timetree.newick
root_to_tip: results/timetree/root_to_tip_regression.pdf
tree_dir: results/tree
tree_legend: results/tree/legend.pdf
divergencetree_image: results/tree/divergence_tree.pdf
timetree_image: results/tree/timetree.pdf
pdb_dir: results/pdbs
variation_analysis_dir: results/variation_analysis
site_variation: results/variation_analysis/site_variability.csv
dms_view_metadata: results/variation_analysis/dms_view_metadata.md
variation_domain_schematic: results/variation_analysis/domain_schematic.pdf
seqs_for_expts_dir: results/seqs_for_expts
seqs_for_expts_diffs: results/seqs_for_expts/n_aa_diffs.pdf
prots_for_expts: results/seqs_for_expts/prots.fasta
