name: CoV_229E_antigenic_drift
channels:
  - etetoolkit
  - bioconda
  - conda-forge
dependencies:
  - ete3
  - hyphy
  - iqtree
  - jupyter_contrib_nbextensions
  - jupyterlab
  - mafft
  - nbdime
  - pandas
  - pip
  - plotnine
  - treetime
  - snakemake
  - pyyaml
