name: CoV_229E_antigenic_drift
channels:
  - etetoolkit
  - bioconda
  - conda-forge
dependencies:
  - ete3=3.1.1
  - hyphy=2.5.15
  - iqtree=2.0.3
  - jupyter_contrib_nbextensions
  - jupyterlab
  - mafft=7.471
  - nbdime
  - pandas
  - pip
  - plotnine
  - python=3.8
  - treetime
  - snakemake
  - pyyaml
  - pip:
    - dna-features-viewer
    - pdb_prot_align
